### ISSUE TITLE
Favicons are not mobile friendly

### ISSUE THREAD

**Issue by stochasticribosome** [adaptyvbio/automancer-docs#1]
Can be seen in `/modules`, `/usage` and `/development`

![Screenshot](https://github.com/adaptyvbio/automancer-docs/assets/131672313/586e00dc-71ac-4cff-8a77-771feb76fa75)

**Comment by slietar** [comment]
Thank you for the report, this seems to be a bug in Safari. I'm not sure what it has to do with favicons or mobile-friendliness though.
